version: '3.7'

services:
  db:
    image: postgres
    volumes:
      - /var/lib/pgsql/:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=root
      - POSTGRES_DB=app_db
    networks:
        docker_my_networks:
                ipv4_address: 172.28.1.1


networks:
  docker_my_networks: 
                external: true

